spring:
  r2dbc:
    url: r2dbc:mysql://friend-mysql:3306/todo_friends
    username: ${username}
    password: ${password}
  h2:
    console:
      enabled: true
  application:
    name: friend
  data:
    r2dbc:
      repositories:
        enabled: true

jwt:
  secret: y7w58a$Ry71afdv87yaod89f230r5!@2desre76wawaqeQrBhXZl0#
  expiration: 25920000

management:
  endpoints:
    web:
      exposure:
        include: "*"
cors:
  allowed-origins: "http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
